name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install Tailscale
      run: choco install tailscale -y

    - name: Connect to Tailscale
      run: |
        tailscale up --authkey $Env:TAILSCALE_AUTHKEY --hostname github-runner --accept-routes
      env:
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Enable RDP
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - name: Enable Firewall
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString "P@ssw0rd!" -AsPlainText -Force)

    - name: Keep Alive
      run: timeout /t 21600
